### ISSUE TITLE
Allow to set custom ServiceAccount name at helm chart

### ISSUE THREAD

**Issue by greatehop** [h3poteto/aws-global-accelerator-controller#162]
Hi

helm chart version **0.7.1** does not allow to set custom ServiceAccount name:

```
% grep rbac -A7 ./aws-global-accelerator-controller/values.yaml
rbac:
  create: true
  # Annotations to add to the service account
  serviceAccount:
    annotations: {}
    # The name of the service account to use.
    # If not set and create is true, a name is generated using the fullname template
    name: "aws-ga-controller"
```
    
```
% helm template test1 ./aws-global-accelerator-controller -f ./aws-global-accelerator-controller/values.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-global-accelerator-controller-manager
  namespace: default
```

I expect "**aws-ga-controller**" instead of "**aws-global-accelerator-controller-manager**", as it's hardcoded at _helper.tpl

```
{{- define "aws-global-accelerator-controller.serviceAccountName" -}}
{{- if .Values.rbac.create }}
    {{- printf "%s-%s" (include "aws-global-accelerator-controller.name" .) "manager" }}
{{- else -}}
    {{ default "default" .Values.rbac.serviceAccount.name }}
{{- end -}}
{{- end -}}
```

**Comment by h3poteto** [comment]
Please set `rbac.create` to `false`.
```yaml
rbac:
  create: false
  serviceAccount:
    name: "aws-ga-controller"
```
